modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/Alex-the-666/CloudStorage/issues" #optional
[[mods]] #mandatory
modId="cloudstorage" #mandatory
version="1.4.0" #mandatory
displayName="Cloud Storage" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/cloud-storage" #optional
authors="Alexthe668, Yosh" #optional
description='''A simple storage solution without the hassle of tech mods - plus a bunch of other fun, sky-themed stuff.'''

[[dependencies.cloudstorage]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[2.4.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.cloudstorage]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"